# Generated by Django 5.2.7 on 2025-10-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_order_service_fee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PayPal", "PayPal"),
                    ("Stripe", "Stripe"),
                    ("Flutterwave", "Flutterwave"),
                    ("Paystack", "Paystack"),
                    ("RazorPay", "RazorPay"),
                ],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
    ]
